# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Rendering of the inventory: CSV for working through, Markdown for the JIRA."""

from __future__ import annotations

import csv
import os
from typing import List

from .inventory import (
    ACTIVE_DOCUMENTED, ACTIVE_UNDOCUMENTED, DEPRECATED_ALIAS, DEPRECATED_CONSTANT,
    DOCUMENTED_ELSEWHERE, EXTERNAL, INTERNAL_PRIVATE, INTERNAL_SKIPLISTED,
    NEEDS_REVIEW, TEST_ONLY, UNUSED, Inventory,
)

CSV_COLUMNS = [
    "key", "status", "recommendation", "module", "documented_in", "xml_value",
    "constant", "declared_at", "declaring_class", "visibility", "default_constant", "default_value",
    "call_site_default", "value_type", "accessors",
    "default_conflict", "read_main", "read_test", "write_main", "write_test",
    "literal_sites", "native_sites", "deprecated_to", "deprecated_constant",
    "skip_reason", "internal_marker", "doc_mentions", "doc_first_seen",
    "declaring_comment", "evidence",
]

_STATUS_ORDER = [
    ACTIVE_UNDOCUMENTED, NEEDS_REVIEW, UNUSED, DOCUMENTED_ELSEWHERE,
    INTERNAL_PRIVATE, TEST_ONLY, INTERNAL_SKIPLISTED, DEPRECATED_ALIAS,
    DEPRECATED_CONSTANT, EXTERNAL, ACTIVE_DOCUMENTED,
]


def write_csv(inv: Inventory, path: str) -> None:
    with open(path, "w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        for status in _STATUS_ORDER:
            for entry in inv.by_status(status):
                row = {name: getattr(entry, name, "") for name in CSV_COLUMNS
                       if name not in ("recommendation", "evidence")}
                row["recommendation"] = entry.recommendation
                row["evidence"] = "; ".join(entry.evidence)
                writer.writerow({k: ("" if v is None else v) for k, v in row.items()})


def _table(rows: List[List[str]], headers: List[str]) -> List[str]:
    lines = ["| " + " | ".join(headers) + " |",
             "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(str(c).replace("|", "\\|") for c in row) + " |")
    return lines


def write_markdown(inv: Inventory, path: str, repo: str) -> None:
    counts = inv.status_counts()
    total = sum(counts.values())
    out: List[str] = []
    out.append("# HDFS configuration property inventory (HDFS-11039)")
    out.append("")
    out.append(f"{total} properties classified. Generated by "
               "`dev-support/hdfs-config-scanner`.")
    out.append("")
    out.append("Extraction is validated against Hadoop's own `TestHdfsConfigFields` and "
               "`TestRBFConfigFields`: with their skip lists applied, the scanner "
               "reproduces a zero diff in both directions, so the numbers below rest on "
               "a checkable foundation.")
    out.append("")

    out.append("## Summary")
    out.append("")
    out.extend(_table(
        [[status, counts.get(status, 0)] for status in _STATUS_ORDER if counts.get(status)],
        ["Status", "Count"]))
    out.append("")

    candidates = inv.by_status(ACTIVE_UNDOCUMENTED)
    out.append(f"## Candidates for documentation ({len(candidates)})")
    out.append("")
    out.append("Read by production code and absent from every `*-default.xml`. "
               "This is the answer to the question asked on the JIRA in 2018.")
    out.append("")
    for module in sorted({e.module for e in candidates}):
        rows = [[f"`{e.key}`", e.declared_at or "", e.default_value or "",
                 f"{e.read_main}"]
                for e in candidates if e.module == module]
        out.append(f"### {module} ({len(rows)})")
        out.append("")
        out.extend(_table(rows, ["Property", "Declared at", "Default", "Reads"]))
        out.append("")

    if inv.by_status(NEEDS_REVIEW):
        out.append(f"## Needs human review ({len(inv.by_status(NEEDS_REVIEW))})")
        out.append("")
        out.extend(_table([[f"`{e.key}`", e.declared_at or "", "; ".join(e.evidence)]
                           for e in inv.by_status(NEEDS_REVIEW)],
                          ["Property", "Declared at", "Evidence"]))
        out.append("")

    if inv.by_status(UNUSED):
        out.append(f"## Declared but never read ({len(inv.by_status(UNUSED))})")
        out.append("")
        out.extend(_table([[f"`{e.key}`", e.declared_at or "", e.constant or ""]
                           for e in inv.by_status(UNUSED)],
                          ["Property", "Declared at", "Constant"]))
        out.append("")

    out.append(f"## Dynamic key families ({len(inv.patterns)})")
    out.append("")
    out.append("Built at runtime, so no scan of literals or constants can enumerate "
               "them; they can only be documented as patterns.")
    out.append("")
    out.extend(_table(
        [[f"`{prefix}`", len(sites),
          os.path.relpath(sites[0].path, repo) + f":{sites[0].line}"]
         for prefix, sites in sorted(inv.patterns.items())],
        ["Prefix / regex", "Sites", "First site"]))
    out.append("")

    contradicted = inv.contradicted_skips
    if contradicted:
        out.append(f"## Skip-list reasons contradicted by the code ({len(contradicted)})")
        out.append("")
        out.append("Excluded from `TestHdfsConfigFields` as deprecated, but still read by "
                   "production code and listed in no `DeprecationDelta` table. The upstream "
                   "comment ends in a question mark; these are the answers.")
        out.append("")
        out.extend(_table(
            [[f"`{e.key}`", e.read_main, e.declared_at or "", e.skip_reason or ""]
             for e in contradicted],
            ["Property", "Reads in production", "Declared at", "Stated reason"]))
        out.append("")

    conflicts = [e for e in inv.entries.values() if e.default_conflict]
    if conflicts:
        out.append(f"## Default value mismatches ({len(conflicts)})")
        out.append("")
        out.append("The documented value differs from the code's default constant.")
        out.append("")
        out.extend(_table([[f"`{e.key}`", e.default_conflict] for e in sorted(
            conflicts, key=lambda x: x.key)], ["Property", "Mismatch"]))
        out.append("")

    if inv.duplicate_xml:
        out.append("## Properties defined more than once")
        out.append("")
        out.append("`Configuration` keeps the last definition, so the earlier block is "
                   "silently ignored.")
        out.append("")
        rows = [[os.path.basename(xml), f"`{name}`"]
                for xml, names in sorted(inv.duplicate_xml.items()) for name in names]
        out.extend(_table(rows, ["File", "Property"]))
        out.append("")

    if inv.not_a_property:
        out.append("## Suspicious call sites")
        out.append("")
        out.append("The key argument folded to a string that is not a property name.")
        out.append("")
        out.extend(_table(
            [[f"`{s.expr}`", f"`{s.resolved_value}`", s.accessor,
              os.path.relpath(s.path, repo) + f":{s.line}"] for s in inv.not_a_property],
            ["Expression", "Resolved to", "Accessor", "Site"]))
        out.append("")

    out.append("## Coverage")
    out.append("")
    out.append(f"- Keys reachable only through the call-site sweep (declared outside the "
               f"ConfigKeys classes the Java tests know about): **{len(inv.e6_only_keys)}**")
    out.append(f"- Call sites whose key is computed at runtime: "
               f"**{len(inv.dynamic_sites)}**")
    out.append(f"- Call sites that could not be parsed at all: "
               f"**{len(inv.unresolved_sites)}**")
    out.append(f"- Plain-literal keys missed by the literal scan (should be 0): "
               f"**{len(inv.literal_regressions)}**")
    out.append("")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out) + "\n")
